# -*- coding: utf-8 -*-
"""Agenda Telefônica.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15KCtXELuQi9PFvGNQ3_3zvs11Cx3JE4_
"""

lista_de_contatos = []

def add_contato():
    nome = str(input('Digite o nome do contato: ')).title()
    numero = int(input('Digite o numero: '))
    lista_add = {}
    lista_add['Nome'] = nome
    lista_add['Numero'] = numero
    lista_de_contatos.append(lista_add)
    print('###############################')
    print('Contato adicionado com sucesso!')
    print('###############################')

def mostra_contato():
    for contato in lista_de_contatos:
        for chave, valor in contato.items():
            print(f'{chave}: valor')

while True:
    print('1-Adicionar contato.')
    print('2-Mostrar contato.')
    print('3-Remover contato.')
    print('4-Editar contato.')
    print('5-Sair.')

    op = int(input('Digite sua opção: '))

    if op == 1:
        add_contato()
    if op == 2:
        mostra_contato()